version: "3.8"

networks:
  network-eventos:
    driver: bridge

services:
  eventos:
    image: mysql:8.3.0
    container_name: "eventosdb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: daker
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: eventos
    networks:
      - network-eventos

  nestjs_api:
    image: nestjs-docker:latest
    container_name: nestjs-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=eventos
      - NODE_ENV=dev
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - eventos
    networks:
      - network-eventos
    env_file:
      - ./dev.env
