version: "3.8"

networks:
  network-eventos:
    driver: bridge
    attachable: true

services:
  eventos:
    image: mysql:8.3.0
    container_name: "eventosdb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: daker
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: eventos
    networks:
      - network-eventos

  app:
    image: nestjs-docker:latest
    container_name: nestjs-docker
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - eventos
    networks:
      - network-eventos
    env_file:
      - ./dev.env
