version: "3.8"

services:
  nestjs_api:
    image: nestjs-docker:latest
    container_name: nestjs-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
