version: "3.8"

services:
  mysql:
    image: mysql:8.2.0
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
