version: "3.8"

services:
  nestjs_api:
    image: nestjs-docker
    container_name: nestjs-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
