version: '3.8'

services:
  mysql_db:
    image: mysql
    container_name: 'eventosdb'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3307

  nestjs_api:
    image: nestjs-docker
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - JWT_SECRET=ThisIsMySecret
      - NODE_ENV=dev
      - DB_HOST=mysql_db
      - DB_PORT=3307
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mysql_db
