version: "3.8"

services:
  mysql_db:
    image: mysql
    container_name: "eventosdb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eventos
      MYSQL_USER: daker
      MYSQL_PASSWORD: secret
      MYSQL_TCP_PORT: 3307

  nestjs_api:
    image: nestjs-docker:latest
    container_name: nestjs-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql_db
      - DB_PORT=3307
      - DB_USER=daker
      - DB_PASS=secret
      - DB_NAME=eventos
      - JWT_SECRET= ThisIsMySecret
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mysql_db

